version: 0.2

env:
  cache:
    paths:
      - '/root/.composer/cache/**/*'
      - '/root/.npm/**/*'
      - 'node_modules/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 25
      php: 8.2
    commands:
      - echo "=== SYSTEM UPDATE ==="
      - apt-get update -y
      - apt-get install -y unzip git curl libpng-dev libonig-dev libxml2-dev zip libsodium-dev

      - echo "=== PHP VERSION & EXTENSIONS ==="
      - php -v
      - php -m

      - echo "=== NODE & NPM VERSION ==="
      - node -v
      - npm -v

      - echo "=== LISTING GLOBAL NPM PACKAGES ==="
      - npm list -g --depth=0 || echo "No global packages installed"

      - echo "=== INSTALLING NPM DEPENDENCIES ==="
      - npm install

      - echo "=== LISTING PROJECT NPM PACKAGES ==="
      - npm list --depth=0

      - echo "=== COMPOSER VERSION & PLATFORM REQUIREMENTS ==="
      - composer --version
      - composer check-platform-reqs || echo "Platform requirements check failed"

      - echo "=== INSTALLING COMPOSER DEPENDENCIES ==="
      - composer install --no-interaction --prefer-dist --optimize-autoloader || composer install --ignore-platform-req=ext-sodium --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE STARTED ==="

  build:
    commands:
      - echo "=== RUNNING BUILD SCRIPTS ==="
      - npm run build

  post_build:
    commands:
      - echo "=== RUNNING LARAVEL OPTIMIZATION ==="
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

      - echo "=== BUILD COMPLETED SUCCESSFULLY ==="
      - echo "Listing all files:"
      - ls -al
      - echo "=== ENVIRONMENT SUMMARY ==="
      - node -v
      - npm -v
      - php -v
      - composer --version
      - php -m
      - npm list --depth=0
      - composer show --installed

artifacts:
  files:
    - '**/*'
