version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
      php: 8.3
    commands:
      - echo "Updating system packages..."
      - apt-get update -y
      - apt-get install -y unzip git curl libpng-dev libonig-dev libxml2-dev zip

      - echo "Installing NPM packages..."
      - npm install

      - echo "Installing Composer dependencies..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install --no-interaction --prefer-dist --optimize-autoloader

      - echo "Checking PHP extensions..."
      - php -m | grep -E 'sodium|curl|mbstring|openssl|xml'

  pre_build:
    commands:
      - echo "Pre-build phase started."

  build:
    commands:
      - echo "Running build scripts..."
      - npm run build

  post_build:
    commands:
      - echo "✅ Build completed successfully!"
      - echo "Listing all files:"
      - ls -al

artifacts:
  files:
    - '**/*'
